import Head from 'next/head'
import Image from 'next/image'
import Banner from '/components/Banner/banner'
import styles from '../styles/Home.module.css'
import Card from '/components/Card/card'

export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log('btn clicked');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src={'/static/hero-image.png'} width={700} height={400} />
        </div>
        <div className={styles.cardLayout}>
          <Card 
            href={'/coffee-store/dark-coffee'}
            imgUrl={'/static/hero-image.png'}
            name={'Dark Coffee'}
            className={styles.card}
          />
          <Card 
            href={'/coffee-store/dark-coffee'}
            imgUrl={'/static/hero-image.png'}
            name={'Dark Coffee'}
            className={styles.card}
          />
          <Card 
            href={'/coffee-store/dark-coffee'}
            imgUrl={'/static/hero-image.png'}
            name={'Dark Coffee'}
            className={styles.card}
          />
        </div>
      </main>
    </div>
  )
}
