import Head from 'next/head'
import Image from 'next/image'
import Banner from '/components/Banner/banner'
import styles from '../styles/Home.module.css'
import Card from '/components/Card/card'
// import coffeeStoresData from '../data/coffee-stores'

// This is server side code, user can inspect in the client console.
// Becasue of this security, we can write all our server side code here.
export async function getStaticProps(context) {

  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: process.env.NEXT_PUBLIC_FOURSQUARE_API_KEY
    }
  };

  const response = await fetch('https://api.foursquare.com/v3/places/search?query=coffee%20shops&ll=39.798458%2C-94.807992&limit=6', options);
  const data = await response.json();

  console.log(data);

  return {
    props: {
      coffeeStores: data.results // will be passed to the page component as props
    },
  }
}

// This is client side code.
// Next js allows front and backend code in the same file.
export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('btn clicked');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src={'/static/hero-image.png'} width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          // react needs a root element, <> </> does that without showing in the DOM
          <>
            <h2 className={styles.heading2}>Coffee Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => {
                return (
                  <Card
                    key={coffeeStore.id}
                    href={`/coffee-store/${coffeeStore.id}`}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    name={coffeeStore.name}
                    className={styles.card}
                  />
                )
              })}
            </div>
          </>
        )}
      </main>
    </div>
  )
}

